version: '3.8'
services:
  app:
    build:
      context: .
    command: bash -c "alembic upgrade head && uvicorn server:app --host 0.0.0.0 --port 80"
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgresql://postgres:passwordl@db:5432/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
