"""New Mi

Revision ID: 5a9462a7687e
Revises: b656d4bff74a
Create Date: 2024-03-13 00:42:11.636884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9462a7687e'
down_revision: Union[str, None] = 'b656d4bff74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_foreign_key(None, 'predictions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_column('predictions', 'user_id')
    # ### end Alembic commands ###
