"""New Migration

Revision ID: 6ad4627b22a7
Revises: 5a9462a7687e
Create Date: 2024-03-13 01:17:05.328694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad4627b22a7'
down_revision: Union[str, None] = '5a9462a7687e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('predictions_user_id_fkey', 'predictions', type_='foreignkey')
    op.drop_column('predictions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('predictions_user_id_fkey', 'predictions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
