"""New Migration

Revision ID: b656d4bff74a
Revises: 
Create Date: 2024-03-13 00:03:12.787971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b656d4bff74a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('prediction', sa.Float(), nullable=True),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('data', sa.String(length=100), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('predictions')
    # ### end Alembic commands ###
