name: Docker Build and Push to GCR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  LOCATION: us-east1-docker.pkg.dev
  PROJECT_ID: premium-valor-418410
  REPO_NAME: crop-rec
  IMAGE_NAME: crop-ai-model
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authorization
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud --quiet auth configure-docker

      - name: Build the Docker image
        run: |
          docker build -t {{ env.LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push the Docker image to Google Cloud Container Registry (GCR)
        run: |
          docker push {{ env.LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
